//! Генерация TypeScript-типов из структур Rust для мини-аппа.

use anyhow::{Context, Result};

use crate::project::Project;

pub fn run(p: &Project) -> Result<()> {
    let src_dir = p.path("src");
    let mut interfaces = Vec::new();

    if let Ok(entries) = std::fs::read_dir(&src_dir) {
        for entry in entries.filter_map(|e| e.ok()) {
            let path = entry.path();
            if path.extension().is_some_and(|e| e == "rs") {
                if let Ok(content) = std::fs::read_to_string(&path) {
                    parse_structs(&content, &mut interfaces);
                }
            }
        }
    }

    let target_dir = if p.has("ui/src") {
        p.path("ui/src")
    } else {
        p.path("ui")
    };
    if !target_dir.exists() {
        std::fs::create_dir_all(&target_dir)?;
    }

    let target_file = target_dir.join("types.ts");
    let header = "/* eslint-disable */\n// Auto-generated by `cargo noro gen-types`. Do not edit manually.\n\n";
    let body = format!("{}{}\n", header, interfaces.join("\n\n"));

    std::fs::write(&target_file, body)
        .with_context(|| format!("не удалось записать {}", target_file.display()))?;

    println!(
        "✓ сгенерированы TypeScript-типы в {}",
        target_file.display()
    );
    Ok(())
}

fn parse_structs(content: &str, out: &mut Vec<String>) {
    let mut lines = content.lines().peekable();
    while let Some(line) = lines.next() {
        let trimmed = line.trim();
        if trimmed.starts_with("pub struct ") && trimmed.ends_with('{') {
            let name = trimmed
                .strip_prefix("pub struct ")
                .unwrap_or("")
                .trim_end_matches('{')
                .trim();
            if name.is_empty() {
                continue;
            }

            let mut fields = Vec::new();
            for f_line in lines.by_ref() {
                let f_trim = f_line.trim();
                if f_trim == "}" {
                    break;
                }
                if f_trim.starts_with("//") || f_trim.starts_with('#') || f_trim.is_empty() {
                    continue;
                }
                if let Some((field_name, field_ty)) = parse_field(f_trim) {
                    fields.push(format!("  {}: {};", field_name, field_ty));
                }
            }

            let iface = format!("export interface {} {{\n{}\n}}", name, fields.join("\n"));
            out.push(iface);
        }
    }
}

fn parse_field(line: &str) -> Option<(String, String)> {
    let line = line
        .strip_prefix("pub ")
        .unwrap_or(line)
        .trim_end_matches(',');
    let parts: Vec<&str> = line.split(':').collect();
    if parts.len() != 2 {
        return None;
    }
    let name = parts[0].trim().to_string();
    let ty = rust_to_ts_type(parts[1].trim());
    Some((name, ty))
}

fn rust_to_ts_type(ty: &str) -> String {
    let ty = ty.trim();
    if ty.starts_with("Option<") && ty.ends_with('>') {
        let inner = &ty[7..ty.len() - 1];
        return format!("{} | null", rust_to_ts_type(inner));
    }
    if ty.starts_with("Vec<") && ty.ends_with('>') {
        let inner = &ty[4..ty.len() - 1];
        return format!("{}[]", rust_to_ts_type(inner));
    }
    match ty {
        "String" | "&str" | "Uuid" => "string".to_string(),
        "i8" | "i16" | "i32" | "i64" | "u8" | "u16" | "u32" | "u64" | "f32" | "f64" | "usize"
        | "isize" => "number".to_string(),
        "bool" => "boolean".to_string(),
        "Value" | "serde_json::Value" => "any".to_string(),
        other => other.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_rust_struct_into_ts_interface() {
        let src = r#"
pub struct UserProfile {
    pub id: Uuid,
    pub name: String,
    pub score: i64,
    pub is_admin: bool,
    pub tags: Vec<String>,
    pub bio: Option<String>,
}
"#;
        let mut out = Vec::new();
        parse_structs(src, &mut out);
        assert_eq!(out.len(), 1);
        assert!(out[0].contains("export interface UserProfile"));
        assert!(out[0].contains("id: string;"));
        assert!(out[0].contains("name: string;"));
        assert!(out[0].contains("score: number;"));
        assert!(out[0].contains("is_admin: boolean;"));
        assert!(out[0].contains("tags: string[];"));
        assert!(out[0].contains("bio: string | null;"));
    }
}
